services:
  db:
    image: mysql:8.3
    container_name: silex_mysql
    environment:
      MYSQL_DATABASE: tools
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_PASSWORD: root
      TZ: Europe/Moscow
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - dbdata:/var/lib/mysql

  backend:
    build: ./backend
    container_name: silex_backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - DB_URL=mysql+pymysql://app:app@db:3306/tools?charset=utf8mb4
      - TZ=Europe/Moscow
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend 
    container_name: silex_frontend
    command: npm run dev -- --host 0.0.0.0 --port 5173
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  dbdata:
